// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4.Models;

namespace Mission4.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20220127063344_third")]
    partial class third
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4.Models.MovieModel", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Title");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Title = "Revenge of the Sith",
                            Category = "Action",
                            Director = "George Lucas",
                            Edited = false,
                            Rating = "PG-13",
                            Year = "2005"
                        },
                        new
                        {
                            Title = "Bourne Ultimatum",
                            Category = "Action",
                            Director = "Paul Greengrass",
                            Edited = false,
                            Rating = "PG-13",
                            Year = "2007"
                        },
                        new
                        {
                            Title = "Endgame",
                            Category = "Action",
                            Director = "Joe and Anthony Russo",
                            Edited = false,
                            Rating = "PG-13",
                            Year = "2018"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
